# Copyright 2016 Daniel Nüst
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
FROM qgis-model-ubuntu
MAINTAINER Daniel Nüst <daniel.nuest@uni-muenster.de>

# This Dockerfile is only an extension of the main Dockerfile to 
# show how data can be copied into the container, instead of
# mounting it at execution time.
COPY data /data

# CMD/ENTRYPOINT can stay the same
